emission_factors:
  Truck: 0.096
  Train: 0.028
  Ship: 0.016
  Plane: 0.602
  Electric Truck: 0.020
  Biofuel Truck: 0.050
  Hydrogen Truck: 0.010

packaging_emissions:
  Plastic: 6.0
  Cardboard: 0.9
  Biodegradable: 0.3
  Reusable: 0.1

packaging_costs:
  Plastic: 1.5
  Cardboard: 0.8
  Biodegradable: 2.0
  Reusable: 3.0

offset_costs:
  Reforestation: 15.0
  Renewable Energy: 20.0
  Methane Capture: 18.0

exchange_rates:
  EUR: 1.0
  USD: 1.06
  AUD: 1.62
  SAR: 3.98

locations:
  USA:
    New York:
      lat: 40.7128
      lon: -74.0060
    Los Angeles:
      lat: 34.0522
      lon: -118.2437
    Chicago:
      lat: 41.8781
      lon: -87.6298
    Houston:
      lat: 29.7604
      lon: -95.3698
    Miami:
      lat: 25.7617
      lon: -80.1918
  Canada:
    Toronto:
      lat: 43.65107
      lon: -79.347015
    Vancouver:
      lat: 49.2827
      lon: -123.1207
    Montreal:
      lat: 45.5017
      lon: -73.5673
    Calgary:
      lat: 51.0447
      lon: -114.0719
    Ottawa:
      lat: 45.4215
      lon: -75.6997
  UK:
    London:
      lat: 51.5074
      lon: -0.1278
    Manchester:
      lat: 53.4808
      lon: -2.2426
    Birmingham:
      lat: 52.4862
      lon: -1.8904
    Glasgow:
      lat: 55.8642
      lon: -4.2518
    Liverpool:
      lat: 53.4084
      lon: -2.9916
  Germany:
    Berlin:
      lat: 52.52
      lon: 13.405
    Munich:
      lat: 48.1351
      lon: 11.5820
    Hamburg:
      lat: 53.5511
      lon: 9.9937
    Frankfurt:
      lat: 50.1109
      lon: 8.6821
    Cologne:
      lat: 50.9375
      lon: 6.9603
  France:
    Paris:
      lat: 48.8566
      lon: 2.3522
    Marseille:
      lat: 43.2965
      lon: 5.3698
    Lyon:
      lat: 45.7640
      lon: 4.8357
    Toulouse:
      lat: 43.6047
      lon: 1.4442
    Nice:
      lat: 43.7102
      lon: 7.2620
  Italy:
    Rome:
      lat: 41.9028
      lon: 12.4964
    Milan:
      lat: 45.4642
      lon: 9.19
    Naples:
      lat: 40.8518
      lon: 14.2681
    Turin:
      lat: 45.0703
      lon: 7.6869
    Palermo:
      lat: 38.1157
      lon: 13.3615
  Spain:
    Madrid:
      lat: 40.4168
      lon: -3.7038
    Barcelona:
      lat: 41.3851
      lon: 2.1734
    Valencia:
      lat: 39.4699
      lon: -0.3763
    Seville:
      lat: 37.3891
      lon: -5.9845
    Bilbao:
      lat: 43.2630
      lon: -2.9350
  Australia:
    Sydney:
      lat: -33.8688
      lon: 151.2093
    Melbourne:
      lat: -37.8136
      lon: 144.9631
    Brisbane:
      lat: -27.4698
      lon: 153.0251
    Perth:
      lat: -31.9505
      lon: 115.8605
    Adelaide:
      lat: -34.9285
      lon: 138.6007
  India:
    Mumbai:
      lat: 19.0760
      lon: 72.8777
    Delhi:
      lat: 28.7041
      lon: 77.1025
    Bangalore:
      lat: 12.9716
      lon: 77.5946
    Chennai:
      lat: 13.0827
      lon: 80.2707
    Kolkata:
      lat: 22.5726
      lon: 88.3639
  China:
    Beijing:
      lat: 39.9042
      lon: 116.4074
    Shanghai:
      lat: 31.2304
      lon: 121.4737
    Guangzhou:
      lat: 23.1291
      lon: 113.2644
    Shenzhen:
      lat: 22.5431
      lon: 114.0579
    Chengdu:
      lat: 30.5728
      lon: 104.0668
  Japan:
    Tokyo:
      lat: 35.6895
      lon: 139.6917
    Osaka:
      lat: 34.6937
      lon: 135.5023
    Kyoto:
      lat: 35.0116
      lon: 135.7681
    Yokohama:
      lat: 35.4437
      lon: 139.6380
    Sapporo:
      lat: 43.0621
      lon: 141.3544
  Brazil:
    São Paulo:
      lat: -23.5505
      lon: -46.6333
    Rio de Janeiro:
      lat: -22.9068
      lon: -43.1729
    Brasília:
      lat: -15.7939
      lon: -47.8828
    Salvador:
      lat: -12.9777
      lon: -38.5016
    Fortaleza:
      lat: -3.7319
      lon: -38.5267
  Russia:
    Moscow:
      lat: 55.7558
      lon: 37.6173
    Saint Petersburg:
      lat: 59.9343
      lon: 30.3351
    Novosibirsk:
      lat: 55.0084
      lon: 82.9357
    Yekaterinburg:
      lat: 56.8389
      lon: 60.6057
    Nizhny Novgorod:
      lat: 56.2965
      lon: 43.9361
  South Africa:
    Johannesburg:
      lat: -26.2041
      lon: 28.0473
    Cape Town:
      lat: -33.9249
      lon: 18.4241
    Durban:
      lat: -29.8587
      lon: 31.0218
    Pretoria:
      lat: -25.7479
      lon: 28.2293
    Port Elizabeth:
      lat: -33.9608
      lon: 25.6022
  Mexico:
    Mexico City:
      lat: 19.4326
      lon: -99.1332
    Guadalajara:
      lat: 20.6597
      lon: -103.3496
    Monterrey:
      lat: 25.6866
      lon: -100.3161
    Puebla:
      lat: 19.0414
      lon: -98.2063
    Tijuana:
      lat: 32.5149
      lon: -117.0382
  Turkey:
    Istanbul:
      lat: 41.0082
      lon: 28.9784
    Ankara:
      lat: 39.9334
      lon: 32.8597
    Izmir:
      lat: 38.4192
      lon: 27.1287
    Bursa:
      lat: 40.1828
      lon: 29.0665
    Adana:
      lat: 37.0
      lon: 35.3213
  South Korea:
    Seoul:
      lat: 37.5665
      lon: 126.9780
    Busan:
      lat: 35.1796
      lon: 129.0756
    Incheon:
      lat: 37.4563
      lon: 126.7052
    Daegu:
      lat: 35.8722
      lon: 128.6025
    Daejeon:
      lat: 36.3504
      lon: 127.3845
  Indonesia:
    Jakarta:
      lat: -6.2088
      lon: 106.8456
    Surabaya:
      lat: -7.2575
      lon: 112.7521
    Bandung:
      lat: -6.9175
      lon: 107.6191
    Medan:
      lat: 3.5952
      lon: 98.6722
    Semarang:
      lat: -6.9667
      lon: 110.4167
  Saudi Arabia:
    Riyadh:
      lat: 24.7136
      lon: 46.6753
    Jeddah:
      lat: 21.4858
      lon: 39.1925
    Mecca:
      lat: 21.3891
      lon: 39.8579
    Medina:
      lat: 24.5247
      lon: 39.5692
    Dammam:
      lat: 26.4207
      lon: 50.0888
  Egypt:
    Cairo:
      lat: 30.0444
      lon: 31.2357
    Alexandria:
      lat: 31.2001
      lon: 29.9187
    Giza:
      lat: 30.0131
      lon: 31.2089
    Shubra El Kheima:
      lat: 30.1286
      lon: 31.2422
    Port Said:
      lat: 31.2653
      lon: 32.3019

carbon_price_eur_per_ton: 65.89 
