locations:
  USA:
    New York: [40.7128, -74.0060]
    Los Angeles: [34.0522, -118.2437]
  Germany:
    Berlin: [52.5200, 13.4050]
emission_factors:
  Truck: 0.12  # kg CO2 per ton-km
  Train: 0.03
  Ship: 0.01
  Plane: 0.9
carbon_price_eur_per_ton: 50.0
exchange_rates:
  USD: 1.1
  GBP: 0.85
packaging_emissions:
  Plastic: 2.5
  Biodegradable: 0.5
packaging_costs:
  Plastic: 0.2
  Biodegradable: 0.3
offset_costs:
  tree_planting: 10.0
  renewable_energy: 15.0
  carbon_credits: 12.0
carbon_price_usd_per_ton: 55.0  # Added for calculate_full_logistics_cost
costs:  # Added for calculate_full_logistics_cost
  air_freight_per_kg: 2.5
  sea_freight_per_teu: 1000.0
  rail_freight_per_kg: 0.1
  inventory_value: 100000.0
  inventory_holding_rate: 0.2
  logistics_time_per_day: 500.0
lead_times:  # Added for calculate_full_logistics_cost
  air_days: 2.0
  multi_modal_days: 10.0
